### ISSUE TITLE
Dynmically update the panel size

### ISSUE THREAD

**Issue by Flomp** [RaviKavaiya/sliding_panel#1]
Hey,

is there a way to dynamically update the widgets size parameter after it has been built? I have dynamic content in the panel and would like to adjust the collapsedHeight and closedHeight attribute accordingly.

Kind regards

**Comment by RaviKavaiya** [comment]
Hello, 
This is possible. Please see the sizing.dart file in example directory for the thing you are needing.

I hope I could solve your query.  Closing this issue for now. But, if you need any other help, feel free to comment.

Thanks.
