### ISSUE TITLE
Opening and closing a modal slidingpanel will cause an app to freeze

### ISSUE THREAD

**Issue by GroovinChip** [RaviKavaiya/sliding_panel#12]
See [#8](https://github.com/RaviKavaiya/sliding_panel/issues/8#issuecomment-603861030)

**Comment by RaviKavaiya** [comment]
@GroovinChip  Hello... Please check the latest version (`v1.0.3`) of the package. It solves this issue as well as your previous issue #11  also. 

Test it. You may now close this issue.

Thanks for your help to improve this package!

**Comment by GroovinChip** [comment]
It seems to be fixed, thanks!
