### ISSUE TITLE
How to remove animation of bodyContent when dragging the panel?

### ISSUE THREAD

**Issue by mdat31** [RaviKavaiya/sliding_panel#18]
When i drag the panel, the body has an effect likes stretching and fading out. How can i remove that effect?

**Comment by RaviKavaiya** [comment]
Hi @manhDat0301 I don't understand your issue.
Your title says something different than what you put in comment.
Please rephrase...

**Comment by mdat31** [comment]
Sorry for my poor English! I can't find help elsewhere so i have to post here

**Comment by RaviKavaiya** [comment]
Hi, you talking about below example?

https://raw.githubusercontent.com/RaviKavaiya/sliding_panel/master/demo/anim_demo.gif

The animation in BLUE color in background?
If yes, then
`parallaxSlideAmount: 0.0` will work...

EDIT: and if you want to remove that BLUE color background as well, then,
`BackdropConfig(enabled: false)`

Let me know if this helps...

**Comment by mdat31** [comment]
Yes, that's right. It worked. Thank you very much.

Using your sliding_panel much easier and better than sliding_up_panel
