### ISSUE TITLE
Panel initially in collapsed mode when in release app, but closed when in debug app.

### ISSUE THREAD

**Issue by DjangoOverloard** [RaviKavaiya/sliding_panel#2]
I want my panel to be initially closed, but somehow when I launch the app in release mode, panel is in collapsed position

**Comment by RaviKavaiya** [comment]
Thanks for opening an issue. Due to some circumstances, I am not able to look into this issue right now. 
I would request you to include the code (suggested to be minimal to reproduce the issue) you are having the problem. As soon as I get free, I would surely be looking into this issue.

**Comment by RaviKavaiya** [comment]
@DjangoOverloard  I checked all the examples present in the [example](https://github.com/RaviKavaiya/sliding_panel/tree/master/example) directory.
I tried running all in debug as well as release modes. I couldn't find any issue. Maybe sharing your code will give me a hint over this issue. :eyes:

**Comment by DjangoOverloard** [comment]
Sure, I will in a few hours, as soon as I get back home. I said expanded in the issue but instead it's actually in collapsed(middle) position when I launch it in release mode

**Comment by RaviKavaiya** [comment]
Ok, as I said, I tried all the examples. Waiting for your sample app and.... Happy to help.

**Comment by DjangoOverloard** [comment]
Oops, I'm so sorry. I've been playing around with google maps along with this panel and it turns out that it was one of the functions that ran differently on different app modes. I am closing this thread. BTW Thank you for the amazing job you've done, I really like your panel. Please make the controller listenable to plug it into the animatedBuilders in the future.
