### ISSUE TITLE
Androidx migration

### ISSUE THREAD

**Issue by gabrielgarciagava** [RaviKavaiya/sliding_panel#22]
Currently, it is recommended that Apps and libraries uses AndroidX instead of Android Support Library. Every new Flutter project will be created as and AndroidX project, and it may be a problem to build AndroidX and Android Support Library together (it is indeed the case with my project, for example).

This document describes how to migrate a flutter project to use AndroidX.
https://flutter.dev/docs/development/androidx-migration

**Comment by RaviKavaiya** [comment]
@gabrielgarciagava Thanks, I will take a look at this...

**Comment by RaviKavaiya** [comment]
@gabrielgarciagava I guess, this is not required for 2 reasons:

1. According to your given link, migration to AndroidX is not compulsory. (https://flutter.dev/docs/development/androidx-migration#what-if-my-app-is-migrated-to-androidx-but-not-all-of-the-plugins-i-use)

2. This package (sliding_panel), doesn't have any plugin code (like, using Android platform, etc). It directly depends on the Flutter SDK. Even if you try to migrate such packages, you would get a warning message stating that there is nothing to migrate. 

Your thoughts?

Thanks.

**Comment by gabrielgarciagava** [comment]
Hello @RaviKavaiya. Thanks for the quick response. My thought is that maybe I'm wrong, and my building is failling by some other reason. After including your package, `flutter build apk --release` does not work anymore, but `flutter build apk --debug` does. It may be something wrong on my project. I will investigate a little more and bring you the results.
I will do that during the next hours.

**Comment by gabrielgarciagava** [comment]
To be more specific, this is EXACTLY the issue I'm facing. https://github.com/flutter/flutter/issues/58247#issuecomment-636500680
As you can see, a lot of people is having this same issue. I just don't know why it started happening after including this library, but it does NOT seem to be a problem with your library at all.
Thanks and sorry for the inconvenience. I think we are good to close this ticket.

**Comment by RaviKavaiya** [comment]
@gabrielgarciagava Thanks, let me know if you have any other issues. For now, I am closing this.
