### ISSUE TITLE
fixed collapsed height?

### ISSUE THREAD

**Issue by hampsterx** [RaviKavaiya/sliding_panel#24]
hi there, cant seem to figure out how to set a min/fixed height.
```
PanelSize(closedHeight: 0.02, expandedHeight: 0.9),
```

this seems only option but its percentage. i am trying to have say 40 px content area shown. is it possible?

**Comment by RaviKavaiya** [comment]
Hello @hampsterx ...
Please have a look at this: https://github.com/RaviKavaiya/sliding_panel/issues/17#issuecomment-629740782

Let me know if this helps!

**Comment by hampsterx** [comment]
ahh sorry didn't check closed issues properly. cheers
