### ISSUE TITLE
setState called after dispose() SlidingPanel

### ISSUE THREAD

**Issue by ghost** [RaviKavaiya/sliding_panel#26]
I have a TextFieldController in my app, but everytime I type anything in it using my keyboard my entire app reloads and shows me the error, 

  `  Error: setState() called after dispose(): _SlidingPanelState#65b14(lifecycle state: defunct, not mounted)`

The error seems related to [SlidingPanel][1] but I'm not sure why is it interfering with TextFieldController. 
   
   ```
SliverToBoxAdapter(
                      child: Container(
                        height: 100,
                        padding: const EdgeInsets.all(20.0),
                        child: TextField(
                          decoration: InputDecoration(
                              border: InputBorder.none,
                              labelText: 'Enter Name',
                              hintText: 'Enter Your Name'),
                        ),
                      ),
                    ),
```

**Comment by RaviKavaiya** [comment]
Please post a reproducible example

**Comment by ghost** [comment]
I'm sorry the issue is not due to SlidingPanel, sorry for the trouble!
