### ISSUE TITLE
When not providing a bodyContent to a modal SlidingSheet there is no shadow for the content behind the sheet

### ISSUE THREAD

**Issue by GroovinChip** [RaviKavaiya/sliding_panel#8]
Code:
```
  /// Show bottom panel
  void showPanel() async {
    final panel = await showModalSlidingPanel(
      context: context,
      panel: (context) => SlidingPanel(
        panelController: _panelController,
        snapping: PanelSnapping.enabled,
        isDraggable: true,
        backPressBehavior: BackPressBehavior.POP,
        isTwoStatePanel: true,
        size: PanelSize(
          closedHeight: 0.5,
          expandedHeight: 1.0,
        ),
        backdropConfig: BackdropConfig(
          enabled: true,
          dragFromBody: true,
        ),
        content: PanelContent(
          headerWidget: PanelHeaderWidget(
            decoration: PanelDecoration(
              backgroundColor: Colors.grey[800]
            ),
            options: PanelHeaderOptions(
              primary: false,
            ),
            headerContent: Padding(
              padding: const EdgeInsets.all(6),
              child: Material(
                elevation: 4,
                child: TextField(
                  onTap: () => _panelController.expand(),
                  decoration: InputDecoration(
                    filled: true,
                    fillColor: Theme.of(context).canvasColor,
                    border: InputBorder.none,
                    prefixIcon: Icon(Icons.search, color: Colors.white),
                    suffixIcon: Icon(Icons.more_vert, color: Colors.white),
                    hintText: 'Instance Search...'
                  ),
                ),
              ),
            ),
          ),
          panelContent: [
            ...
          ],
        ),
      ),
    );
  }
```

Screenshot: ![image](https://user-images.githubusercontent.com/4250470/77497825-a1c2d600-6e24-11ea-9731-81f25b5bd1db.png)

**Comment by RaviKavaiya** [comment]
@GroovinChip  Thanks...

(To be clear, this problem has no relation with bodyContent)

There are actually 2 solutions to your problem:
But first, why this happened???

> The panel can show shadow only if the panel is NOT in closed state. The shadow will start appearing once the panel starts expanding...

Now, solutions:
**Solution - 1.**
(This one is the recommended).
- Make your panel three-state, by removing `isTwoState` parameter.
- Then, specify a `collapsedHeight` in `size` parameter.
- That should show shadow in the background as soon as you leave the `closedHeight` of the panel.
- You can also specify the `initialState` to further customise the behaviour of panel when you first open the panel.

- *Note that,* you specified `closedHeight` as `0.5`, so I may also assume that you want to show something like persistent widget in your screen. In that case, I would simply suggest you to avoid `showModalSlidingPanel` as that is something not built for what you want to achieve.


**Solution - 2.**
(This will do the trick without any refactoring, but NOT recommended)

- Just specify `effectInCollapsedMode: false` in `backdropConfig`. You will get the shadow you want.
- **BUT,** there are also some limitations. (e.g., You won't receive gestures below the panel). I can't write all them here, but you can refer the documentation of this parameter.
- After doing this, to close the panel, you can use `PanelController.dismiss()`. (`close()` will simply not work, because you have put `closedHeight` to 0.5)

I hope I could solve your query. If you got your solution, you can close this issue. Otherwise, you can comment...

**Comment by GroovinChip** [comment]
The behavior I want to achieve is like the Relay for Reddit Android app where there is no popup sheet, then it opens to a specific height, which can either snapped to the top of the screen or dismissed away by swiping down.

So, question, then: when the panel is not shown at all, is it considered closed or collapsed? When The panel is semi-open, as in not expanded to fill the whole screen, is that collapsed?

**Comment by GroovinChip** [comment]
I seem to have gotten it:
- by explicitly setting `isTwoState` to `false`
- by setting `initialState` to collapsed
- by setting `PanelSize` to 

```
PanelSize(
       closedHeight: 0.0,
       collapsedHeight: 0.5,
       expandedHeight: 1.0,
     ),
```

Thank you for your help!

**Comment by GroovinChip** [comment]
Weirdly, now once I've opened and closed the panel once I can't get it to open again. Actually my whole app seems to freeze 🤔

**Comment by RaviKavaiya** [comment]
Ok, let me try this.
But before this, can you provide your code snippet (as you have made changes)?

EDIT: I think this may happen due to the parameter set `draggableInClosed: true` in `backdropConfig`. If yes, this **should be false**...

**Comment by GroovinChip** [comment]
Here is the full current code:
```
void showPanel() async {
    final panel = await showModalSlidingPanel(
      context: context,
      panel: (context) => SlidingPanel(
        panelController: _panelController,
        snapping: PanelSnapping.enabled,
        isDraggable: true,
        initialState: InitialPanelState.collapsed,
        isTwoStatePanel: false,
        size: PanelSize(
          closedHeight: 0.0,
          collapsedHeight: 0.5,
          expandedHeight: expSize,
        ),
        backdropConfig: BackdropConfig(
          enabled: true,
          dragFromBody: true,
          opacity: 0.9,
        ),
        content: PanelContent(
          /// The 'instance search' textfield resides here
          headerWidget: PanelHeaderWidget(
            decoration: PanelDecoration(backgroundColor: Colors.grey[800]),
            options: PanelHeaderOptions(
              primary: false,
            ),
            headerContent: Padding(
              padding: const EdgeInsets.all(6),
              child: Material(
                elevation: 4,
                child: TextField(
                  onTap: () => _panelController.expand(),
                  decoration: InputDecoration(
                    filled: true,
                    fillColor: Theme.of(context).canvasColor,
                    border: InputBorder.none,
                    prefixIcon: Icon(Icons.search, color: Colors.white),
                    suffixIcon: Icon(Icons.more_vert, color: Colors.white),
                    hintText: 'Instance Search...',
                  ),
                ),
              ),
            ),
          ),

          /// The list of timelines and instances resides here
          panelContent: [
            Material(
              child: GroovinExpansionTile(
                title: Text('Timelines'),
                initiallyExpanded: true,
                children: <Widget>[
                  ListTile(
                    dense: true,
                    leading: CircleAvatar(
                      radius: 16,
                      backgroundColor: Theme.of(context).primaryColor,
                      child: Icon(MdiIcons.home, color: Colors.white),
                    ),
                    title: Text('Local'),
                    onTap: () {
                      _appBloc.timeline.add('Local');
                      Navigator.pop(context);
                    },
                  ),
                  ListTile(
                    dense: true,
                    leading: CircleAvatar(
                      radius: 16,
                      backgroundColor: Theme.of(context).primaryColor,
                      child: Icon(MdiIcons.accountGroup, color: Colors.white),
                    ),
                    title: Text('Following'),
                    onTap: () {
                      _appBloc.timeline.add('Following');
                      Navigator.pop(context);
                    },
                  ),
                  ListTile(
                    dense: true,
                    leading: CircleAvatar(
                      radius: 16,
                      backgroundColor: Theme.of(context).primaryColor,
                      child: Icon(MdiIcons.earth, color: Colors.white),
                    ),
                    title: Text('Global'),
                    onTap: () {
                      _appBloc.timeline.add('Global');
                      Navigator.pop(context);
                    },
                  ),
                ],
              ),
            ),
            Material(
              child: GroovinExpansionTile(
                title: Text('Instances'),
                children: <Widget>[
                  ListTile(
                    dense: true,
                    leading: CircleAvatar(
                      radius: 16,
                      backgroundColor: Theme.of(context).primaryColor,
                      child: Icon(MdiIcons.mastodon, color: Colors.white),
                    ),
                    title: Text('Dummy instance'),
                    trailing: PopupMenuButton(
                      icon: Icon(Icons.more_vert),
                      onSelected: (selection) {},
                      itemBuilder: (context) => [
                        PopupMenuItem(
                          child: Text('Instance info'),
                          value: 'Info',
                        ),
                        PopupMenuItem(
                          child: Text('Remove'),
                          value: 'Remove',
                        ),
                      ],
                    ),
                    onTap: () {},
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
```
After opening and closing the panel a few times, the app freezes.

**Comment by RaviKavaiya** [comment]
Hi, thanks! I found the culprit!
Actually, this would be happening when you close the panel *very* slowly. Below is the description of what takes place (For your understanding only, go below for solution)...

- You have specified `PanelSnapping.enabled` (That's fine).
- Also, you have specified `closedHeight: 0.0` and `dragFromBody: true`, so you can control the panel from the background (when panel is **not** at 0.0 position).
- The moment you slide the panel downwards (towards 0.0 position), and actually reach to 0.0 position, the panel is **still** there, (open, not closed, but hidden). And you think your app is freezed. Its not, the panel is *still* receiving gestures, but *as the position is 0.0*, the `dragFromBody` no longer helps!!! (And that creates confusion to the panel)
- So, the problem won't come if you drag quickly. But for slow drags, there is a solution...

---
#### Here is the solution:

I would solve this issue with 2 simple steps:
- Firstly, I would specify `PanelSnapping.forced`, so the panel will snap to nearest position, no matter how slowly the user slides the panel.
- Second, specify `panelClosedOptions: PanelClosedOptions(detachDragging: true)`. This will do the trick you are wanting: 

When you slide the panel downwards (drag speed won't matter, fast or very slow), the moment it detects that you have reached the position at `closedHeight` (read again, closedHeight, not only 0.0 position), it will immediately detach (disconnect) the panel dragging (sliding) functionality from the panel and you re-gain the control of your app! The panel will no longer wait for the user to drag it. 

*Pro tip:* Explore the `panelClosedOptions`, if you haven't done so yet. It has some useful functions.

**CAUTION!** When you specify `detachDragging`, only a `PanelController` can re-open the panel. (This won't be an issue in your case, as you specify `closedHeight: 0.0`).

Let me know if this solves your issue.

**Comment by GroovinChip** [comment]
This didn't do the trick, I'll see if I can get a gif of what's going on for you today.

**Comment by RaviKavaiya** [comment]
@GroovinChip I investigated again and found that this is indeed a bug. Thanks for reporting. I would request you to create a new issue for this (the app freezing issue), so that I can mention in the changelog.

**Comment by GroovinChip** [comment]
Hey man, will do. Want me to close this issue?

**Comment by RaviKavaiya** [comment]
The original issue is solved (no shadow displayed). 
Issue of getting app freezed will be tracked in #12
